apiversion: v1
clusters:
- cluster
    certificate-authority-data: ${eks_certificate_authority_data}
    server: ${eks_cluster_endpoint}
  name: ${eks_cluster_arn}
contexts:
- context:
    cluster:  ${eks_cluster_arn}
    user: ${eks_cluster_arn}
  name: ${eks_cluster_arn}
current-context:  ${eks_cluster_arn}
kind: Config
preferences:  {}
users: 
- name: ${eks_cluster_arn}
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
        - --region
        - ${eks_cluster_region}
        - eks
        - get-token
        - --cluster-name
        - ${eks_cluster_name}
        command:  aws